### ISSUE TITLE
Error: Taking infinite time to deploy the `starter kit` to fastly edge.

### ISSUE THREAD

**Issue by byteshiva** [fastly/compute-actions#11]
Since there is no default `service_id` value in fastly.toml file, the actions step deployment is gone in an infinite loop.

it's been more than 5mins to deploy the `starter kit` to fastly edge.

The error says it's looking for service_id in `fastly.toml`. It's going in a loop, Maybe I need to cancel the deployment.

![image](https://user-images.githubusercontent.com/10637299/149137110-a746b52e-38f3-4e4c-b38e-374e45e555e0.png)

![image](https://user-images.githubusercontent.com/10637299/149136827-ce611088-0aa5-483f-b5eb-334d827cf27c.png)

_Originally posted by @byteshiva in https://github.com/fastly/compute-actions/issues/9#issuecomment-1010977446_

**Comment by kailan** [comment]
Hi @byteshiva, thanks for the report

Do you have a service ID set as a workflow parameter or environment variable? The service ID will be fetched from the following sources, from highest to lowest precedence:
 1. GitHub Actions `service_id` param (equivalent of passing `--service-id` to the CLI)
 2. `FASTLY_SERVICE_ID` environment variable
 3. fastly.toml `service_id` field

**Comment by byteshiva** [comment]
Assumption:
My Mistake, I assumed a new service would automatically be created when this starter kit is deployed using api_token from Github!

Question:
1. In this case do I need to get a `domain name` to test some basic scenario or will the fastly create a random subdomain on its domain name.
2. I have manually created a service and I'm unable to activate it because it requires a domain name to complete service activation.
![image](https://user-images.githubusercontent.com/10637299/149249941-fe2d4d64-305d-45d3-af59-706b6135eed4.png)

 3. Can I use any existing services from fastly to push this content!

![image](https://user-images.githubusercontent.com/10637299/149250674-b49d7f70-131e-4f15-b978-a1b20b892f80.png)

**Comment by byteshiva** [comment]
Notes:

1. fastly compute init unable to fetch contents from GitHub private repository, I think I may have to provide the GITHUB API token to fetch private repository. I don't see any configuration in fastly CLI. 

First Try initializing the private repo.
```
root@3d365fc0a1be:/home/clientinfo# fastly compute init --from=https://github.com/byteshiva/clientInfo

Creating a new Compute@Edge project (using --from to locate package template).

Press ^C at any time to quit.

Name: [clientinfo] 
Description: 
Author: [chnshivaind@gmail.com] 

✓ Initializing...
- Fetching package template...
✗ Fetching package template...

ERROR: failed to get package: 404 Not Found.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md

ERROR: there was a problem updating the versioning information for the Fastly CLI:

Get "https://developer.fastly.com/api/internal/cli-config": context deadline exceeded.
```

Second Try 

```
If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
root@3d365fc0a1be:/home/clientinfo# 
root@3d365fc0a1be:/home/clientinfo# fastly compute init --from=https://github.com/byteshiva/clientInfo

Creating a new Compute@Edge project (using --from to locate package template).

Press ^C at any time to quit.

Name: [clientinfo] 
Description: 
Author: [chnshivaind@gmail.com] 

✓ Initializing...
✗ Fetching package template...

ERROR: failed to get package: 404 Not Found.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md

ERROR: there was a problem updating the versioning information for the Fastly CLI:

Get "https://developer.fastly.com/api/internal/cli-config": context deadline exceeded.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
root@3d365fc0a1be:/home/clientinfo# fastly compute init --from=https://github.com/byteshiva/clientInfo^C

```

Now I changed the permission of the private repo to public. 

2. I'm able to fetch any public GITHUB repos using `fastly cli` init
```
root@3d365fc0a1be:/home/clientinfo# fastly compute init --from=https://github.com/byteshiva/clientInfo

Creating a new Compute@Edge project (using --from to locate package template).

Press ^C at any time to quit.

Name: [clientinfo] 
Description: 
Author: [chnshivaind@gmail.com] 

✓ Initializing...
/ Fetching package template...
✓ Fetching package template...
✓ Updating package manifest...
✓ Initializing package...

Initialized package clientinfo to:
	/home/clientinfo

To publish the package (build and deploy), run:
	fastly compute publish

To learn about deploying Compute@Edge projects using third-party orchestration tools, visit:
	https://developer.fastly.com/learning/integrations/orchestration/


SUCCESS: Initialized package clientinfo

ERROR: there was a problem updating the versioning information for the Fastly CLI:

Get "https://developer.fastly.com/api/internal/cli-config": context deadline exceeded.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
root@3d365fc0a1be:/home/clientinfo# 

```

4. Now I'm able to push the repo and I can get the service id. 
```
root@3d365fc0a1be:/home/clientinfo# fastly compute publish 
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local javascript toolchain...
✓ Building package using javascript toolchain...
✓ Creating package archive...

SUCCESS: Built package 'clientinfo' (pkg/clientinfo.tar.gz)


There is no Fastly service associated with this package. To connect to an existing service
add the Service ID to the fastly.toml file, otherwise follow the prompts to create a
service now.

Press ^C at any time to quit.

Create new service: [y/N] y

✓ Initializing...
✓ Creating service...

Domain: [asdaldskj-asdjadsk-asdasdjlkasjd.edgecompute.app]   <<< I've garbled the sub-domain

Backend (hostname or IP address, or leave blank to stop adding backends): 

✓ Creating domain 'asdaldskj-asdjadsk-asdasdjlkasjd.edgecompute.app'...
✓ Uploading package...
✓ Activating version...

Manage this service at:
	https://manage.fastly.com/configure/services/asdlkajsdlkajsdlkjasd  <<< I've garbled the service id

View this service at:
	https://asdaldskj-asdjadsk-asdasdjlkasjd.edgecompute.app   


SUCCESS: Deployed package (service asdasdasdkjasdjasdk, version 1) <<< I've garbled the service id

ERROR: there was a problem updating the versioning information for the Fastly CLI:

Get "https://developer.fastly.com/api/internal/cli-config": context deadline exceeded.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
root@3d365fc0a1be:/home/clientinfo# 
```

**Comment by byteshiva** [comment]
Deploying another instance:

Taking time in `Post deploy ` step:
https://github.com/byteshiva/clientInfo/runs/4799229225?check_suite_focus=true

![image](https://user-images.githubusercontent.com/10637299/149271565-c4d402d0-f349-4553-bcd9-3bff8a1fd92d.png)


ps:-
Am I missing something here?

**Comment by kailan** [comment]
> 1. In this case do I need to get a `domain name` to test some basic scenario or will the fastly create a random subdomain on its domain name.

> 2. I have manually created a service and I'm unable to activate it because it requires a domain name to complete service activation.

For Compute@Edge apps, you can create a free subdomain of `edgecompute.app` (e.g. `my-cool-app.edgecompute.app`). You will need one of these as a minimum.


> 3. Can I use any existing services from fastly to push this content!

Yes, absolutely! As long as the API token you're using has access to the service, you can update the `service_id` in fastly.toml to use an existing service's ID and it will deploy over what was previously there.

> After updating the service id, still, I see it's taking more than 5 mins to upload. I assume the deployment shouldn't take this much time.

I think you will need to pass the `FASTLY_SERVICE_ID` environment variable on to the action, e.g.:
```yml
    - name: Deploy to Compute@Edge
      uses: fastly/compute-actions@main
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
        FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}`
```

**Comment by byteshiva** [comment]
> 
> I think you will need to pass the `FASTLY_SERVICE_ID` environment variable onto the action, e.g.:
> 
> ```yaml
>     - name: Deploy to Compute@Edge
>       uses: fastly/compute-actions@main
>       env:
>         FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
>         FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}
> ```

I assume the `service_id` is case sensitive, I see in the log of `compute action` has changed `service_id` to lowercase and thus throws `404` error saying service not found 
![image](https://user-images.githubusercontent.com/10637299/149318429-4c05bc81-175d-47f1-b7d0-db3a1d0b13fe.png)

**Comment by kailan** [comment]
Hi @byteshiva, I can see that the service ID there is correct so the 404 is likely down to the token not having access to that service.

Make sure that when creating the token, you have selected the correct service, and that you have enabled `global` scope. `global:read` will not be sufficient to deploy.

Let me know if this doesn't work 👍

**Comment by byteshiva** [comment]
> Hi @byteshiva, I can see that the service ID there is correct so the 404 is likely down to the token not having access to that service.
> 
> Make sure that when creating the token, you have selected the correct service, and that you have enabled `global` scope. `global:read` will not be sufficient to deploy.
> 
> Let me know if this doesn't work 👍

It was my mistake, I had tied wrong service is with Api token of global read acess. Now that I had created another API token(global all acess) tied with right service made it work!

Thanks @kailan

**Comment by kailan** [comment]
Fantastic, glad to hear! Have fun building on Compute@Edge :)

**Comment by byteshiva** [comment]
@kailan 
Notes and Observation:

1. I see `service id` is been shown in debug log if the API token has incorrect permissions. Is it okay to make it visible in the actions log? Can we have an attribute to set it off?
2. Also I see fastly CLI doesn't read private Github repo. I may be missing something here?
3. If the user misses entering the `service id` in GitHub secrets or `fastly. toml` and other places, it indirectly consumes Github Action API hours by checking for `service id` for an infinite amount of time. Can we have `Short-circuit` in code to avoid consuming ACTION API hours?

**Comment by kailan** [comment]
> 1. I see `service id` is been shown in debug log if the API token has incorrect permissions. Is it okay to make it visible in the actions log? Can we have an attribute to set it off?

Service IDs aren't typically considered secret – there's nothing you can do with one that you couldn't without it. Additionally, our standard Deliver services advertise their service ID publicly by default so this should not be a cause for concern.

> 2. Also I see fastly CLI doesn't read private Github repo. I may be missing something here?

I think you are correct, this is not currently supported. I would be happy to open a issue for you in the https://github.com/fastly/cli repo.

> 3. If the user misses entering the `service id` in GitHub secrets or `fastly.toml` and other places, it indirectly consumes Github Action API hours by checking for `service id` for an infinite amount of time. Can we have `Short-circuit` in code to avoid consuming ACTION API hours?

This is a great call-out, I've opened an issue to track this (https://github.com/fastly/compute-actions/issues/12) and aim to get it resolved soon. Thanks for the report.

**Comment by byteshiva** [comment]
> 
> > 2. Also I see fastly CLI doesn't read private Github repo. I may be missing something here?
> 
> I think you are correct, this is not currently supported. I would be happy to open an issue for you in the https://github.com/fastly/cli repo.

I've created an issue at https://github.com/fastly/cli/issues/510
