### ISSUE TITLE
[bug] accidental service deletion when PR is cleaned up for failed deployment

### ISSUE THREAD

**Issue by NeilHanlon** [fastly/compute-actions#52]
If a preview fails to deploy, then when a PR is closed, the call to `fastly service delete`, despite being called with --service-name, falls back to the service id in fastly.toml, leading to accidental deletion of the main service.

Not sure exactly what the fix is here--possibly in the action, make sure the service exist firsts? Alternatively, perhaps the fastly CLI should error out if given inconsistent instructions (i.e., service-name passed should **never** fall back to a stored value, IMO).

ref: https://github.com/rocky-linux/docs.rockylinux.org/actions/runs/10162431351/job/28104475417#step:7:36

**Comment by JakeChampion** [comment]
I agree the CLI should have a different behavior here 👍 
Do you know if an issue has been raised in the https://github.com/fastly/cli ?

**Comment by NeilHanlon** [comment]
> I agree the CLI should have a different behavior here 👍 Do you know if an issue has been raised in the https://github.com/fastly/cli ?

I have not yet, but I will this evening or tomorrow :)

**Comment by kailan** [comment]
This was resolved in the CLI and the fix will be released shortly. Thanks for the report!
