### ISSUE TITLE
v9 throws error when deploying

### ISSUE THREAD

**Issue by adjwillig** [fastly/compute-actions#60]
We're deploying our service with the following step:

      - name: Deploy Compute@Edge Package
        uses: fastly/compute-actions/deploy@main
        with:
          service_id: ${{ env.serviceID }}
          comment: 'Deployed via GitHub Actions'

With the release of v9 this morning, it's now throwing the error `Error: artifact.create is not a function` after deploying. This will prevent the subsequent steps from running, but the service will be deployed.

**Comment by ozwaldorf** [comment]
Getting the same errors

**Comment by ozwaldorf** [comment]
Will there be a release with the fix soon?

**Comment by kpfleming** [comment]
It's in-process in #63.
