### ISSUE TITLE
Unable to Deploy in Fastly

### ISSUE THREAD

**Issue by byteshiva** [fastly/compute-actions#9]
Error while deploying in fastly using GitHub action

![image](https://user-images.githubusercontent.com/10637299/149068374-e6f2d1e0-c87a-4625-bdb9-48c417363282.png)

**Comment by byteshiva** [comment]
![image](https://user-images.githubusercontent.com/10637299/149069339-107fee89-a0d9-43b7-958f-518ad22d6c9f.png)

I'm using this starter kit to deploy in `fastly` edge
https://github.com/fastly/compute-starter-kit-javascript-default

**Comment by kailan** [comment]
Hi @byteshiva – sorry to break your workflow.

Could you replace `fastly/compute-actions@main` with `fastly/compute-actions@main-verify` and verify that the workflow runs successfully?

**Comment by byteshiva** [comment]
it's been more than 5mins to deploy the `starter kit` to fastly edge.

The error says it's looking for service_id in `fastly.toml`. It's going in a loop, Maybe I need to cancel the deployment.

![image](https://user-images.githubusercontent.com/10637299/149137110-a746b52e-38f3-4e4c-b38e-374e45e555e0.png)

![image](https://user-images.githubusercontent.com/10637299/149136827-ce611088-0aa5-483f-b5eb-334d827cf27c.png)
